# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
    -   id: check-yaml  # Validates YAML file syntax
    -   id: check-added-large-files  # Prevents accidentally committing large files
    -   id: debug-statements  # Checks for debugger imports and py37+ breakpoint() calls
    -   id: check-executables-have-shebangs  # Checks that all executable files have a shebang
    -   id: name-tests-test  # Renames test files to match the "test_" prefix
    -   id: requirements-txt-fixer  # Fixes issues in requirements.txt files
    -   id: trailing-whitespace  # Removes trailing whitespace
    -   id: end-of-file-fixer  # Ensures files end with a newline
    -   id: check-merge-conflict  # Checks for merge conflict strings
    -   id: check-json  # Validates JSON file syntax
    -   id: check-toml  # Validates TOML file syntax
    -   id: mixed-line-ending  # Replaces mixed line endings
        args: ['--fix=lf']
    -   id: detect-private-key  # Detects private keys
-   repo: https://github.com/psf/black
    rev: 25.1.0
    hooks:
    -   id: black  # Python code formatter
        args: ['-S', --line-length=100]
        language_version: python3
-   repo: https://github.com/pycqa/flake8
    rev: '7.3.0'
    hooks:
    -   id: flake8  # Python linter for style guide enforcement
        args: [--max-line-length=100, --extend-ignore=E203,W503]
-   repo: https://github.com/pycqa/isort
    rev: 6.0.1
    hooks:
      - id: isort  # Sorts Python imports
        name: isort (python)
        args: [--profile=black, --line-length=100, --skip-gitignore]  # Compatible with black formatter
-   repo: https://github.com/econchick/interrogate
    rev: 1.7.0
    hooks:
      - id: interrogate  # Checks Python docstring coverage
        args: [-vv, --ignore-init-method, --fail-under=100]
-   repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.17.1
    hooks:
    -   id: mypy  # Static type checker for Python
        args: [--strict, --ignore-missing-imports, --no-error-summary]
        additional_dependencies: [tokenize-rt==5.2.0, types-pyyaml]
-   repo: https://github.com/asottile/add-trailing-comma
    rev: v3.2.0
    hooks:
    -   id: add-trailing-comma  # Automatically adds trailing commas to Python code
        args: [--py36-plus]
-   repo: https://github.com/PyCQA/bandit
    rev: 1.8.6
    hooks:
    -   id: bandit  # Security linter for Python code
        args: [-r, --skip, B101]
-   repo: https://github.com/pypa/pip-audit
    rev: v2.9.0
    hooks:
    -   id: pip-audit  # Scans Python dependencies for known vulnerabilities
        args: [--desc]
-   repo: https://github.com/Yelp/detect-secrets
    rev: v1.5.0
    hooks:
    -   id: detect-secrets  # Scans for secrets and sensitive information
        args: ['--baseline', '.secrets.baseline']
        exclude: package.lock.json
-   repo: https://github.com/codespell-project/codespell
    rev: v2.4.1
    hooks:
    -   id: codespell  # Checks for common misspellings
        additional_dependencies: [tomli]
-   repo: https://github.com/pre-commit/mirrors-prettier
    rev: v4.0.0-alpha.8
    hooks:
    -   id: prettier  # Code formatter for JS, JSON, YAML, Markdown, etc.
        types_or: [javascript, jsx, ts, tsx, json, yaml, markdown]
