# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
    -   id: check-yaml  # Validates YAML file syntax
    -   id: check-added-large-files  # Prevents accidentally committing large files
    -   id: debug-statements  # Checks for debugger imports and py37+ breakpoint() calls
-   repo: https://github.com/psf/black
    rev: 23.12.1
    hooks:
    -   id: black  # Python code formatter
        args: ['-S']
-   repo: https://github.com/pycqa/flake8
    rev: '7.0.0'
    hooks:
    -   id: flake8  # Python linter for style guide enforcement
        args: [--max-line-length=88]
-   repo: https://github.com/pycqa/isort
    rev: 5.13.2
    hooks:
      - id: isort  # Sorts Python imports
        name: isort (python)
-   repo: https://github.com/econchick/interrogate
    rev: 1.5.0
    hooks:
      - id: interrogate  # Checks Python docstring coverage
        args: [-vv, --ignore-init-method, --fail-under=100]
-   repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.8.0
    hooks:
    -   id: mypy  # Static type checker for Python
        args: [--strict, --ignore-missing-imports]
        additional_dependencies: [tokenize-rt==5.2.0]
-   repo: https://github.com/asottile/add-trailing-comma
    rev: v3.1.0
    hooks:
    -   id: add-trailing-comma  # Automatically adds trailing commas to Python code
-   repo: https://github.com/PyCQA/bandit
    rev: 1.7.5
    hooks:
    -   id: bandit  # Security linter for Python code
        args: [-r, --skip, B101]
-   repo: https://github.com/pypa/pip-audit
    rev: v2.6.1
    hooks:
    -   id: pip-audit  # Scans Python dependencies for known vulnerabilities
        args: [--desc]
-   repo: https://github.com/Yelp/detect-secrets
    rev: v1.4.0
    hooks:
    -   id: detect-secrets  # Scans for secrets and sensitive information
        args: ['--baseline', '.secrets.baseline']
